version: "3.9"
services:

    nginx:
        container_name: ${APP_TITLE:-nginx}
        build: ./docker/nginx
        links:
            - php
        volumes:
            - ${PWD}:/usr/share/nginx/www
        ports:
            - ${APP_PORT:-8000}:80

    php:
        container_name: php8-fpm
        build: ./docker/php
        volumes:
            - ${PWD}:/usr/share/nginx/www
        env_file:
            - ./.env

networks:
    default:
        external: true
        name: ${APP_DOCKER_NETWORK}
