version: "3.9"
services:

    nginx:
        container_name: nginx-DD-framwork
        build: ./docker/nginx
        links:
            - php
        volumes:
            - ${PWD}:/usr/share/nginx/www
        ports:
            - 8000:80

    php:
        container_name: php-DD-framwork
        build: ./docker/php
        volumes:
            - ${PWD}:/usr/share/nginx/www
        working_dir: ${PWD}:/usr/share/nginx/www
        env_file:
            - ./.env

networks:
    default:
        external: true
        name: production
