version: "3.9"
services:

    nginx:
        container_name: nginx-didishop
        build: ./Docker/nginx
        links:
            - php
        volumes:
            - ${PWD}:/usr/share/nginx/www
        ports:
            - 8000:80

    php:
        container_name: php-didishop
        build: ./Docker/php
        volumes:
            - ${PWD}:/usr/share/nginx/www
        working_dir: ${PWD}:/usr/share/nginx/www
        env_file:
            - ./.env

networks:
    default:
        external: true
        name: production
